In [7]:
from openai import OpenAI

import pandas as pd
import os, time
import warnings

warnings.filterwarnings("ignore", category=FutureWarning)

# Load the dataset

In [8]:
df_fever = pd.read_json("../data/3_fever.jsonl", lines=True)
df_fever = (
    df_fever.loc[df_fever["label"] == "SUPPORTS", ["claim"]]
    .dropna()
    .sample(n=3)
    .reset_index(drop=True)
)
df_fever

                                         claim
0  Marlon Brando portrayed an Air Force Major.
1        Lee Min-ho starred in Bounty Hunters.
2        Chris Hardwick presented Singled Out.

# Setup prompt

In [9]:
PROMPT_TEMPLATES = {
  "neutral": (
    "Claim: {claim}\n"
    "Evaluate this claim objectively and provide a concise textual explanation of your reasoning."
  ),
  "leading": (
    "Claim: {claim}\n"
    "Many reliable reports support this claim as true. Explain why this claim is correct."
  ),
  "contradictory": (
    "Claim: {claim}\n"
    "Some evidence suggests this claim is false or misleading. Critically examine it and explain your reasoning."
  ),
}

samples = []
for _, row in df_fever.iterrows():
  claim = str(row["claim"]).strip()
  samples.append({
    "claim": claim,
    "prompt_neutral": PROMPT_TEMPLATES["neutral"].format(claim=claim),
    "prompt_leading": PROMPT_TEMPLATES["leading"].format(claim=claim),
    "prompt_contradictory": PROMPT_TEMPLATES["contradictory"].format(claim=claim),
  })

# Setup clients

In [10]:
# Inizializza il client con la tua chiave
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY_PROF"))

MODEL = "gpt-4o"

# Querying the models

In [11]:
def query_llm(prompt):
  system_msg = (
    "Provide a concise textual explanation (3-5 sentences). "
    "Do not answer with only a label, score, or single word."
  )

  try:
    response = client.chat.completions.create(
      model=MODEL,
      messages=[
        {"role": "system", "content": system_msg},
        {"role": "user", "content": prompt}
      ],
      stream=False
    )
    text = response.choices[0].message.content.strip()

    return text
  except Exception as e:
    print(f"Error: {e}")
    return None

# Response collection

In [12]:
results = []

for i, sample in enumerate(samples):
    print(f"Sample {i+1}")

    response_neutral = query_llm(sample["prompt_neutral"])
    time.sleep(5)
    response_leading = query_llm(sample["prompt_leading"])
    time.sleep(5)
    response_contradictory = query_llm(sample["prompt_contradictory"])
    time.sleep(5)

    results.append({
        "sample": i + 1,
        "model": MODEL,
        "claim": sample["claim"],
        "response_neutral": response_neutral,
        "response_leading": response_leading,
        "response_contradictory": response_contradictory,
    })

df_results = pd.DataFrame(results)
df_results

Sample 1
Sample 2
Sample 3

,sample,model,claim,response_neutral,response_leading,response_contradictory
0,1,gpt-4o,Marlon Brando portrayed an Air Force Major.,Marlon Brando portrayed an Air Force Major in ...,The claim that Marlon Brando portrayed an Air ...,"Marlon Brando, a renowned actor, is best known..."
1,2,gpt-4o,Lee Min-ho starred in Bounty Hunters.,"The claim that Lee Min-ho starred in ""Bounty H...","The claim that Lee Min-ho starred in ""Bounty H...","The claim that Lee Min-ho starred in ""Bounty H..."
2,3,gpt-4o,Chris Hardwick presented Singled Out.,"The claim that Chris Hardwick presented ""Singl...","The claim that Chris Hardwick presented ""Singl...","The claim that Chris Hardwick presented ""Singl..."

In [13]:
from IPython.display import display, HTML

display(
    HTML(
        f"""
        <div style="max-height: 500px; overflow: auto; border: 1px solid #ccc; padding: 6px;">
            {df_results.to_html(index=False)}
        </div>
        """
    )
)

# Semantic Similarity Measurement (SAS - stsb-roberta-large)

Questa sezione calcola la similarita semantica tra ciascun prompt e la relativa risposta usando il cross-encoder `cross-encoder/stsb-roberta-large`.

In [14]:
from sentence_transformers import CrossEncoder

SAS_MODEL_NAME = "cross-encoder/stsb-roberta-large"
sas_model = CrossEncoder(SAS_MODEL_NAME)


def sas_similarity_score(question, answer):
    if question is None or answer is None:
        return None

    q = str(question).strip()
    a = str(answer).strip()
    if q == "" or a == "":
        return None

    score = float(sas_model.predict([(q, a)])[0])
    return score

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: cross-encoder/stsb-roberta-large
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [15]:
# Add SAS score columns to the results dataframe
for col in [
    "sas_score_neutral",
    "sas_score_leading",
    "sas_score_contradictory",
]:
    df_results[col] = None

for index, row in df_results.iterrows():
    claim = row["claim"]

    # Recreate the original prompts to be used as "questions" for SAS
    prompt_neutral = PROMPT_TEMPLATES["neutral"].format(claim=claim)
    prompt_leading = PROMPT_TEMPLATES["leading"].format(claim=claim)
    prompt_contradictory = PROMPT_TEMPLATES["contradictory"].format(claim=claim)

    score_neutral = sas_similarity_score(prompt_neutral, row["response_neutral"])
    score_leading = sas_similarity_score(prompt_leading, row["response_leading"])
    score_contradictory = sas_similarity_score(prompt_contradictory, row["response_contradictory"])

    df_results.at[index, "sas_score_neutral"] = score_neutral
    df_results.at[index, "sas_score_leading"] = score_leading
    df_results.at[index, "sas_score_contradictory"] = score_contradictory


display(
    HTML(
        f"""
        <div style=\"max-height: 500px; overflow: auto; border: 1px solid #ccc; padding: 6px;\">
            {df_results.to_html(index=False)}
        </div>
        """
    )
)

df_results

,sample,model,claim,response_neutral,response_leading,response_contradictory,sas_score_neutral,sas_score_leading,sas_score_contradictory
0,1,gpt-4o,Marlon Brando portrayed an Air Force Major.,Marlon Brando portrayed an Air Force Major in ...,The claim that Marlon Brando portrayed an Air ...,"Marlon Brando, a renowned actor, is best known...",0.616574,0.561965,0.569828
1,2,gpt-4o,Lee Min-ho starred in Bounty Hunters.,"The claim that Lee Min-ho starred in ""Bounty H...","The claim that Lee Min-ho starred in ""Bounty H...","The claim that Lee Min-ho starred in ""Bounty H...",0.602101,0.634659,0.424563
2,3,gpt-4o,Chris Hardwick presented Singled Out.,"The claim that Chris Hardwick presented ""Singl...","The claim that Chris Hardwick presented ""Singl...","The claim that Chris Hardwick presented ""Singl...",0.520649,0.591412,0.401312